ratatui 0.28.1 -> 0.29.0
Only one code adjustment is required. Some `toggle_switch.rs` rustdoc
example code now needs to pass a ref to `render_widget()`:

```
error[E0277]: the trait bound `ToggleSwitch<'_>: Widget` is not satisfied
  --> src/toggle_switch.rs:24:21
   |
10 | frame.render_widget(toggle_switch, frame.area());
   |       ------------- ^^^^^^^^^^^^^ the trait `Widget` is not implemented for `ToggleSwitch<'_>`
   |       |
   |       required by a bound introduced by this call
```